/***
            Bismillahir Rahmanir Rahim
            Start with the name of Allah, who created you!!!
            Author : MD Aftab Uddin Bhuiyan
            Department of CSE, Dhaka international University, Bangladesh.
***/

#include <iostream>
#include<cmath>
using namespace std;

int main() {
	 int n;
	 cin>>n;
	 int c=0,s=0;
	 for(int i=0;i<n;i++){
		 int a,b;
		 cin>>a>>b;
	  	    s-=a;
		    s+=b;
		 c=max(c,s);

	 }
	 cout<<c<<endl;

	return 0;
}
