/***
            Bismillahir Rahmanir Rahim
            Start with the name of Allah, who created you!!!
            Author : MD Aftab Uddin Bhuiyan
            Department of CSE, Dhaka international University, Bangladesh.
***/


#include<iostream>
#include<algorithm>
#include<cstring>
using namespace std;

int main()
{
	char A[101];
	int i,l,c=0;
 
	cin>>A;
	l = strlen(A);
	sort(A,A+l);
    for(i=0;i<l;i++)
    {
        if(A[i] != A[i+1])
        {
            c++;
        }
    }
    if(c%2==0)
    {
        cout<<"CHAT WITH HER!\n";
    }
    else
    {
        cout<<"IGNORE HIM!\n";
    }
}
