/***
            Bismillahir Rahmanir Rahim
            Start with the name of Allah, who created you!!!
            Author : MD Aftab Uddin Bhuiyan
            Department of CSE, Dhaka international University, Bangladesh.
***/


#include <iostream>
#include <cstring>
using namespace std;

int main() {
	string s;
	cin>>s;
	int up=0,low=0,i;
	for(i=0;i<s.size();i++){
	    if(isupper(s[i])){
	        up++;
	    }else{
	         low++;
	    }
	}
	if(up>low){
	    char ch;
	    for( i=0;i<s.size();i++){
	        ch=toupper(s[i]);
	        cout<<ch;
	    }
	}else{
	    char ch;
	    for(i=0;i<s.size();i++){
	        ch=tolower(s[i]);
	        cout<<ch;
	    }
	}
	return 0;
}
