/***
            Bismillahir Rahmanir Rahim
            Start with the name of Allah, who created you!!!
            Author : MD Aftab Uddin Bhuiyan
            Department of CSE, Dhaka international University, Bangladesh.
***/


#include<bits/stdc++.h>
using namespace std;
int main()
{
    int n,bills=0;
    int a[]={100,20,10,5,1};
    cin>>n;
    for(int i=0; i<5; i++)
    {
        bills+=n/a[i];
        n=n%a[i];
    }
    cout<<bills<<endl;
    return 0;
}
